//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string SessionId { get; set; }
        public string ShipToFirstname { get; set; }
        public string ShipToLastName { get; set; }
        public string ShipToEmail { get; set; }
        public string ShipToPhone { get; set; }
        public string ShipToAddress { get; set; }
        public int ShipToCityId { get; set; }
        public int ShipToCountryId { get; set; }
        public int ShipToStateId { get; set; }
        public string ShipToZip { get; set; }
        public string BillToFirstName { get; set; }
        public string BillToLastName { get; set; }
        public string BillToEmail { get; set; }
        public string BillToPhone { get; set; }
        public string BillToAddress { get; set; }
        public int BillToCityId { get; set; }
        public int BillToCountryId { get; set; }
        public int BillToStateId { get; set; }
        public string BillToZip { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public Nullable<double> ShippingAmount { get; set; }
        public Nullable<double> Tax { get; set; }
        public double GrandTotal { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string Host { get; set; }
        public string OS { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
